In [2]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from scripts.fraud_data_pipeline import FraudDataPipeline
from scripts.fraude_eda_pipeline import FraudEDAPipeline

df = FraudDataPipeline(
    "../data/raw/Fraud_Data.csv",
    "../data/raw/IpAddress_to_Country.csv"
).run()

eda = FraudEDAPipeline(df).run()

eda["class_ratio"]
eda["fraud_by_country"]

d:\week-5\fraud-detection\src\utils\data_cleaning.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df[col].fillna(self.df[col].median(), inplace=True)
d:\week-5\fraud-detection\src\utils\data_cleaning.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df[col].fillna(self.df[col].mode()[0], inplace=True)
d:\week-5\fraud-detection\src\utils\data_cleaning.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df[col].fillna(self.df[col].median(), inplace=True)
d:\week-5\fraud-detection\src\utils\data_cleaning.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df[col].fillna(self.df[col].mode()[0], inplace=True)
d:\week-5\fraud-detection\src\utils\data_cleaning.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df[col].fillna(self.df[col].median(), inplace=True)
d:\week-5\fraud-detection\src\utils\data_cleaning.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df[col].fillna(self.df[col].median(), inplace=True)
d:\week-5\fraud-detection\src\utils\data_cleaning.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df[col].fillna(self.df[col].median(), inplace=True)
d:\week-5\fraud-detection\src\utils\feature_engineering.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  self.df["purchase_time"] = self.df["purchase_time"].fillna(method="ffill")

class           0         1
country
Unknown  0.906354  0.093646

In [4]:
eda["class_counts"]

class
0    136961
1     14151
Name: count, dtype: int64

In [5]:
eda["univariate"]

,purchase_time,user_id,signup_time,purchase_value,age,ip_address,class,ip_int,hour_of_day,day_of_week,time_since_signup,txn_count_1h
count,151112,151112.000000,151112,151112.000000,151112.000000,1.511120e+05,151112.000000,0.0,151112.000000,151112.000000,1.511120e+05,151112.0
mean,2015-06-16 02:56:38.759952640,200171.040970,2015-04-20 00:56:09.511329024,36.935372,33.140704,2.152145e+09,0.093646,NaN,11.521593,3.011819,4.932029e+06,1.0
min,2015-01-01 00:00:44,2.000000,2015-01-01 00:00:42,9.000000,18.000000,5.209350e+04,0.000000,NaN,0.000000,0.000000,1.000000e+00,1.0
25%,2015-04-18 14:41:25.500000,100642.500000,2015-02-18 09:52:48.500000,22.000000,27.000000,1.085934e+09,0.000000,NaN,6.000000,1.000000,2.186754e+06,1.0
50%,2015-06-18 13:46:17.500000,199958.000000,2015-04-19 04:41:30,35.000000,33.000000,2.154770e+09,0.000000,NaN,12.000000,3.000000,4.926346e+06,1.0
75%,2015-08-17 18:48:31.500000,300054.000000,2015-06-18 14:47:22.750000128,49.000000,39.000000,3.243258e+09,0.000000,NaN,17.000000,5.000000,7.644524e+06,1.0
max,2015-12-16 02:56:05,400000.000000,2015-08-18 04:40:29,154.000000,76.000000,4.294850e+09,1.000000,NaN,23.000000,6.000000,1.036797e+07,1.0
std,NaN,115369.285024,NaN,18.322762,8.617733,1.248497e+09,0.291336,NaN,6.912474,2.006203,3.126263e+06,0.0

In [6]:
eda["bivariate"]

,user_id,purchase_value,age,ip_address,ip_int,hour_of_day,day_of_week,time_since_signup,txn_count_1h
class,,,,,,,,,
0,200098.920123,36.929418,33.122356,2.154235e+09,NaN,11.517249,2.999606,5.191179e+06,1.0
1,200869.065366,36.993004,33.318281,2.131918e+09,NaN,11.563635,3.130026,2.423842e+06,1.0